fix(help): wrong full help sep rendering
charmbracelet/bubbles pull request #554
Opened 2024-07-14 13:35 UTC by luevano

No matter the available horizontal space, sometimes the separator for the full help is not rendered. For example:

![image](https://github.com/user-attachments/assets/60b58f2f-883b-47d7-b0ec-efafc4319238)
![image](https://github.com/user-attachments/assets/54b5013e-5680-46c9-b9bf-c95d079864ea)

The issue is that the check if a separator needs to be rendered is done on `group` (the column) and not `groups` (the total columns). With this fixed:

![image](https://github.com/user-attachments/assets/e924efc8-329e-4085-9ed3-b20e6e6a40e4)
![image](https://github.com/user-attachments/assets/d33bd27a-b556-43a0-899f-bd403186abd1)

However, when there is enough space for the separator but not the column itself it renders the separator at the end:
![image](https://github.com/user-attachments/assets/375d9757-ce87-4fa3-86fe-494f141e8ab4)

This PR fixes these 2 issues and matches the behavior of the short help (adding a tail if needed/possible, rendering the separator inline, etc.). Behavior now:
![image](https://github.com/user-attachments/assets/0538624e-a296-4f72-a1e2-fc7397e2643d)
![image](https://github.com/user-attachments/assets/36c3eda1-a5e4-482b-94f4-99bbeea48032)
![image](https://github.com/user-attachments/assets/5e9b9e40-131c-4d70-bed4-04050927da0e)

2024-08-13 18:34 UTC, caarlos0 approved these changes

2024-08-15 18:28 UTC, bashbunni commented
We should add a test for this

2024-09-19 18:15 UTC, meowgorithm commented
So I think this makes sense. @luevano, do you mind providing some minimal code we can use to replicate this (in addition to a test)?

2024-10-10 19:09 UTC, meowgorithm requested changes
Alright, this is a solid fix. It just needs a test and we're good to go.

2024-10-10 19:50 UTC, meowgorithm commented
Alright, I have a test for this which I'll merge next. Thanks again for the excellent PR, and for your great patience with the one, @luevano.

2024-10-10 19:50 UTC, merged

2024-10-10 20:06 UTC, luevano commented
Hey @meowgorithm, sorry forgot about the request for the minimal code and test, been busy with work stuff lately; thanks for keeping things moving here for me!

2024-10-10 20:21 UTC, meowgorithm commented
No worries, thanks again for the great PR!